// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/telemetry.proto

package grpcstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DaemonId    string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*TelemetryEvent_HostDiscovered
	//	*TelemetryEvent_ConnectionFlow
	//	*TelemetryEvent_AdTicket
	//	*TelemetryEvent_WirelessBeacon
	Event         isTelemetryEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *TelemetryEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TelemetryEvent) GetEvent() isTelemetryEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TelemetryEvent) GetHostDiscovered() *HostDiscovered {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_HostDiscovered); ok {
			return x.HostDiscovered
		}
	}
	return nil
}

func (x *TelemetryEvent) GetConnectionFlow() *ConnectionFlow {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_ConnectionFlow); ok {
			return x.ConnectionFlow
		}
	}
	return nil
}

func (x *TelemetryEvent) GetAdTicket() *ActiveDirectoryTicket {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_AdTicket); ok {
			return x.AdTicket
		}
	}
	return nil
}

func (x *TelemetryEvent) GetWirelessBeacon() *WirelessBeacon {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_WirelessBeacon); ok {
			return x.WirelessBeacon
		}
	}
	return nil
}

type isTelemetryEvent_Event interface {
	isTelemetryEvent_Event()
}

type TelemetryEvent_HostDiscovered struct {
	HostDiscovered *HostDiscovered `protobuf:"bytes,3,opt,name=host_discovered,json=hostDiscovered,proto3,oneof"`
}

type TelemetryEvent_ConnectionFlow struct {
	ConnectionFlow *ConnectionFlow `protobuf:"bytes,4,opt,name=connection_flow,json=connectionFlow,proto3,oneof"`
}

type TelemetryEvent_AdTicket struct {
	AdTicket *ActiveDirectoryTicket `protobuf:"bytes,5,opt,name=ad_ticket,json=adTicket,proto3,oneof"`
}

type TelemetryEvent_WirelessBeacon struct {
	WirelessBeacon *WirelessBeacon `protobuf:"bytes,6,opt,name=wireless_beacon,json=wirelessBeacon,proto3,oneof"`
}

func (*TelemetryEvent_HostDiscovered) isTelemetryEvent_Event() {}

func (*TelemetryEvent_ConnectionFlow) isTelemetryEvent_Event() {}

func (*TelemetryEvent_AdTicket) isTelemetryEvent_Event() {}

func (*TelemetryEvent_WirelessBeacon) isTelemetryEvent_Event() {}

type HostDiscovered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	InferredOs    string                 `protobuf:"bytes,3,opt,name=inferred_os,json=inferredOs,proto3" json:"inferred_os,omitempty"`
	OpenPorts     []string               `protobuf:"bytes,4,rep,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`
	Hostnames     []string               `protobuf:"bytes,5,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostDiscovered) Reset() {
	*x = HostDiscovered{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostDiscovered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDiscovered) ProtoMessage() {}

func (x *HostDiscovered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDiscovered.ProtoReflect.Descriptor instead.
func (*HostDiscovered) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *HostDiscovered) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostDiscovered) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *HostDiscovered) GetInferredOs() string {
	if x != nil {
		return x.InferredOs
	}
	return ""
}

func (x *HostDiscovered) GetOpenPorts() []string {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *HostDiscovered) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

type ConnectionFlow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SrcIp            string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp            string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort          int32                  `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort          int32                  `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol         string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,6,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	EntropyScore     float32                `protobuf:"fixed32,7,opt,name=entropy_score,json=entropyScore,proto3" json:"entropy_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionFlow) Reset() {
	*x = ConnectionFlow{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionFlow) ProtoMessage() {}

func (x *ConnectionFlow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionFlow.ProtoReflect.Descriptor instead.
func (*ConnectionFlow) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionFlow) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *ConnectionFlow) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *ConnectionFlow) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *ConnectionFlow) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ConnectionFlow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionFlow) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *ConnectionFlow) GetEntropyScore() float32 {
	if x != nil {
		return x.EntropyScore
	}
	return 0
}

type ActiveDirectoryTicket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrincipalName  string                 `protobuf:"bytes,1,opt,name=principal_name,json=principalName,proto3" json:"principal_name,omitempty"`
	Realm          string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	TicketType     string                 `protobuf:"bytes,3,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"` // AS-REQ, TGS-REQ
	EncryptionType string                 `protobuf:"bytes,4,opt,name=encryption_type,json=encryptionType,proto3" json:"encryption_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActiveDirectoryTicket) Reset() {
	*x = ActiveDirectoryTicket{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveDirectoryTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveDirectoryTicket) ProtoMessage() {}

func (x *ActiveDirectoryTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveDirectoryTicket.ProtoReflect.Descriptor instead.
func (*ActiveDirectoryTicket) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *ActiveDirectoryTicket) GetPrincipalName() string {
	if x != nil {
		return x.PrincipalName
	}
	return ""
}

func (x *ActiveDirectoryTicket) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *ActiveDirectoryTicket) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *ActiveDirectoryTicket) GetEncryptionType() string {
	if x != nil {
		return x.EncryptionType
	}
	return ""
}

type WirelessBeacon struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Bssid              string                 `protobuf:"bytes,1,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Ssid               string                 `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	SignalStrengthDbm  int32                  `protobuf:"varint,3,opt,name=signal_strength_dbm,json=signalStrengthDbm,proto3" json:"signal_strength_dbm,omitempty"`
	EncryptionProtocol string                 `protobuf:"bytes,4,opt,name=encryption_protocol,json=encryptionProtocol,proto3" json:"encryption_protocol,omitempty"`
	Channel            int32                  `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WirelessBeacon) Reset() {
	*x = WirelessBeacon{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirelessBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirelessBeacon) ProtoMessage() {}

func (x *WirelessBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirelessBeacon.ProtoReflect.Descriptor instead.
func (*WirelessBeacon) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *WirelessBeacon) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WirelessBeacon) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WirelessBeacon) GetSignalStrengthDbm() int32 {
	if x != nil {
		return x.SignalStrengthDbm
	}
	return 0
}

func (x *WirelessBeacon) GetEncryptionProtocol() string {
	if x != nil {
		return x.EncryptionProtocol
	}
	return ""
}

func (x *WirelessBeacon) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type TelemetryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The server can stream back dynamic BPF filters or instructions
	BlocklistIps  []string `protobuf:"bytes,3,rep,name=blocklist_ips,json=blocklistIps,proto3" json:"blocklist_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryResponse) GetBlocklistIps() []string {
	if x != nil {
		return x.BlocklistIps
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaemonId      string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	AlertType     string                 `protobuf:"bytes,2,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // ROGUE_AP, C2_BEACON, STEGANOGRAPHY
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *Alert) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *Alert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type AlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ActionTaken   string                 `protobuf:"bytes,2,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *AlertResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *AlertResponse) GetActionTaken() string {
	if x != nil {
		return x.ActionTaken
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\x14darkapi.telemetry.v1\"\x98\x03\n" +
	"\x0eTelemetryEvent\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12O\n" +
	"\x0fhost_discovered\x18\x03 \x01(\v2$.darkapi.telemetry.v1.HostDiscoveredH\x00R\x0ehostDiscovered\x12O\n" +
	"\x0fconnection_flow\x18\x04 \x01(\v2$.darkapi.telemetry.v1.ConnectionFlowH\x00R\x0econnectionFlow\x12J\n" +
	"\tad_ticket\x18\x05 \x01(\v2+.darkapi.telemetry.v1.ActiveDirectoryTicketH\x00R\badTicket\x12O\n" +
	"\x0fwireless_beacon\x18\x06 \x01(\v2$.darkapi.telemetry.v1.WirelessBeaconH\x00R\x0ewirelessBeaconB\a\n" +
	"\x05event\"\x90\x01\n" +
	"\x0eHostDiscovered\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x1f\n" +
	"\vinferred_os\x18\x03 \x01(\tR\n" +
	"inferredOs\x12\x1d\n" +
	"\n" +
	"open_ports\x18\x04 \x03(\tR\topenPorts\x12\x1c\n" +
	"\thostnames\x18\x05 \x03(\tR\thostnames\"\xe2\x01\n" +
	"\x0eConnectionFlow\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\x05R\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\x05R\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12+\n" +
	"\x11bytes_transferred\x18\x06 \x01(\x03R\x10bytesTransferred\x12#\n" +
	"\rentropy_score\x18\a \x01(\x02R\fentropyScore\"\x9e\x01\n" +
	"\x15ActiveDirectoryTicket\x12%\n" +
	"\x0eprincipal_name\x18\x01 \x01(\tR\rprincipalName\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x1f\n" +
	"\vticket_type\x18\x03 \x01(\tR\n" +
	"ticketType\x12'\n" +
	"\x0fencryption_type\x18\x04 \x01(\tR\x0eencryptionType\"\xb5\x01\n" +
	"\x0eWirelessBeacon\x12\x14\n" +
	"\x05bssid\x18\x01 \x01(\tR\x05bssid\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12.\n" +
	"\x13signal_strength_dbm\x18\x03 \x01(\x05R\x11signalStrengthDbm\x12/\n" +
	"\x13encryption_protocol\x18\x04 \x01(\tR\x12encryptionProtocol\x12\x18\n" +
	"\achannel\x18\x05 \x01(\x05R\achannel\"l\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rblocklist_ips\x18\x03 \x03(\tR\fblocklistIps\"\xa4\x01\n" +
	"\x05Alert\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x02 \x01(\tR\talertType\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"V\n" +
	"\rAlertResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12!\n" +
	"\faction_taken\x18\x02 \x01(\tR\vactionTaken2\xca\x01\n" +
	"\x12DarkProbeTelemetry\x12a\n" +
	"\fStreamEvents\x12$.darkapi.telemetry.v1.TelemetryEvent\x1a'.darkapi.telemetry.v1.TelemetryResponse\"\x00(\x01\x12Q\n" +
	"\vReportAlert\x12\x1b.darkapi.telemetry.v1.Alert\x1a#.darkapi.telemetry.v1.AlertResponse\"\x00B?Z=github.com/straticus1/ads-darkapi-io/darkprobe/pkg/grpcstreamb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_telemetry_proto_goTypes = []any{
	(*TelemetryEvent)(nil),        // 0: darkapi.telemetry.v1.TelemetryEvent
	(*HostDiscovered)(nil),        // 1: darkapi.telemetry.v1.HostDiscovered
	(*ConnectionFlow)(nil),        // 2: darkapi.telemetry.v1.ConnectionFlow
	(*ActiveDirectoryTicket)(nil), // 3: darkapi.telemetry.v1.ActiveDirectoryTicket
	(*WirelessBeacon)(nil),        // 4: darkapi.telemetry.v1.WirelessBeacon
	(*TelemetryResponse)(nil),     // 5: darkapi.telemetry.v1.TelemetryResponse
	(*Alert)(nil),                 // 6: darkapi.telemetry.v1.Alert
	(*AlertResponse)(nil),         // 7: darkapi.telemetry.v1.AlertResponse
}
var file_proto_telemetry_proto_depIdxs = []int32{
	1, // 0: darkapi.telemetry.v1.TelemetryEvent.host_discovered:type_name -> darkapi.telemetry.v1.HostDiscovered
	2, // 1: darkapi.telemetry.v1.TelemetryEvent.connection_flow:type_name -> darkapi.telemetry.v1.ConnectionFlow
	3, // 2: darkapi.telemetry.v1.TelemetryEvent.ad_ticket:type_name -> darkapi.telemetry.v1.ActiveDirectoryTicket
	4, // 3: darkapi.telemetry.v1.TelemetryEvent.wireless_beacon:type_name -> darkapi.telemetry.v1.WirelessBeacon
	0, // 4: darkapi.telemetry.v1.DarkProbeTelemetry.StreamEvents:input_type -> darkapi.telemetry.v1.TelemetryEvent
	6, // 5: darkapi.telemetry.v1.DarkProbeTelemetry.ReportAlert:input_type -> darkapi.telemetry.v1.Alert
	5, // 6: darkapi.telemetry.v1.DarkProbeTelemetry.StreamEvents:output_type -> darkapi.telemetry.v1.TelemetryResponse
	7, // 7: darkapi.telemetry.v1.DarkProbeTelemetry.ReportAlert:output_type -> darkapi.telemetry.v1.AlertResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	file_proto_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryEvent_HostDiscovered)(nil),
		(*TelemetryEvent_ConnectionFlow)(nil),
		(*TelemetryEvent_AdTicket)(nil),
		(*TelemetryEvent_WirelessBeacon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
