// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/darkprobe.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DarkProbeService_Discover_FullMethodName   = "/darkprobe.DarkProbeService/Discover"
	DarkProbeService_Sniff_FullMethodName      = "/darkprobe.DarkProbeService/Sniff"
	DarkProbeService_TLSInspect_FullMethodName = "/darkprobe.DarkProbeService/TLSInspect"
)

// DarkProbeServiceClient is the client API for DarkProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service exposing DarkProbe functionality
type DarkProbeServiceClient interface {
	// Discover network hosts
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// Sniff traffic (streaming responses)
	Sniff(ctx context.Context, in *SniffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SniffResponse], error)
	// TLS inspection of a domain
	TLSInspect(ctx context.Context, in *TLSInspectRequest, opts ...grpc.CallOption) (*TLSInspectResponse, error)
}

type darkProbeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDarkProbeServiceClient(cc grpc.ClientConnInterface) DarkProbeServiceClient {
	return &darkProbeServiceClient{cc}
}

func (c *darkProbeServiceClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, DarkProbeService_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkProbeServiceClient) Sniff(ctx context.Context, in *SniffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SniffResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DarkProbeService_ServiceDesc.Streams[0], DarkProbeService_Sniff_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SniffRequest, SniffResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DarkProbeService_SniffClient = grpc.ServerStreamingClient[SniffResponse]

func (c *darkProbeServiceClient) TLSInspect(ctx context.Context, in *TLSInspectRequest, opts ...grpc.CallOption) (*TLSInspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TLSInspectResponse)
	err := c.cc.Invoke(ctx, DarkProbeService_TLSInspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DarkProbeServiceServer is the server API for DarkProbeService service.
// All implementations must embed UnimplementedDarkProbeServiceServer
// for forward compatibility.
//
// Service exposing DarkProbe functionality
type DarkProbeServiceServer interface {
	// Discover network hosts
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	// Sniff traffic (streaming responses)
	Sniff(*SniffRequest, grpc.ServerStreamingServer[SniffResponse]) error
	// TLS inspection of a domain
	TLSInspect(context.Context, *TLSInspectRequest) (*TLSInspectResponse, error)
	mustEmbedUnimplementedDarkProbeServiceServer()
}

// UnimplementedDarkProbeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDarkProbeServiceServer struct{}

func (UnimplementedDarkProbeServiceServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedDarkProbeServiceServer) Sniff(*SniffRequest, grpc.ServerStreamingServer[SniffResponse]) error {
	return status.Error(codes.Unimplemented, "method Sniff not implemented")
}
func (UnimplementedDarkProbeServiceServer) TLSInspect(context.Context, *TLSInspectRequest) (*TLSInspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TLSInspect not implemented")
}
func (UnimplementedDarkProbeServiceServer) mustEmbedUnimplementedDarkProbeServiceServer() {}
func (UnimplementedDarkProbeServiceServer) testEmbeddedByValue()                          {}

// UnsafeDarkProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DarkProbeServiceServer will
// result in compilation errors.
type UnsafeDarkProbeServiceServer interface {
	mustEmbedUnimplementedDarkProbeServiceServer()
}

func RegisterDarkProbeServiceServer(s grpc.ServiceRegistrar, srv DarkProbeServiceServer) {
	// If the following call panics, it indicates UnimplementedDarkProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DarkProbeService_ServiceDesc, srv)
}

func _DarkProbeService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkProbeServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkProbeService_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkProbeServiceServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkProbeService_Sniff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SniffRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DarkProbeServiceServer).Sniff(m, &grpc.GenericServerStream[SniffRequest, SniffResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DarkProbeService_SniffServer = grpc.ServerStreamingServer[SniffResponse]

func _DarkProbeService_TLSInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkProbeServiceServer).TLSInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkProbeService_TLSInspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkProbeServiceServer).TLSInspect(ctx, req.(*TLSInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DarkProbeService_ServiceDesc is the grpc.ServiceDesc for DarkProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DarkProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkprobe.DarkProbeService",
	HandlerType: (*DarkProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _DarkProbeService_Discover_Handler,
		},
		{
			MethodName: "TLSInspect",
			Handler:    _DarkProbeService_TLSInspect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sniff",
			Handler:       _DarkProbeService_Sniff_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/darkprobe.proto",
}
