// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/darkprobe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        string                 `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"` // CIDR subnet to scan
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_darkprobe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	OpenPorts     []string               `protobuf:"bytes,4,rep,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_darkprobe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{1}
}

func (x *HostInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetOpenPorts() []string {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostInfo            `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_proto_darkprobe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverResponse) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type SniffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"` // duration string e.g. "30s"
	MonitorMode   bool                   `protobuf:"varint,3,opt,name=monitor_mode,json=monitorMode,proto3" json:"monitor_mode,omitempty"`
	WpaSsid       string                 `protobuf:"bytes,4,opt,name=wpa_ssid,json=wpaSsid,proto3" json:"wpa_ssid,omitempty"`
	WpaPsk        string                 `protobuf:"bytes,5,opt,name=wpa_psk,json=wpaPsk,proto3" json:"wpa_psk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SniffRequest) Reset() {
	*x = SniffRequest{}
	mi := &file_proto_darkprobe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SniffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SniffRequest) ProtoMessage() {}

func (x *SniffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SniffRequest.ProtoReflect.Descriptor instead.
func (*SniffRequest) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{3}
}

func (x *SniffRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *SniffRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *SniffRequest) GetMonitorMode() bool {
	if x != nil {
		return x.MonitorMode
	}
	return false
}

func (x *SniffRequest) GetWpaSsid() string {
	if x != nil {
		return x.WpaSsid
	}
	return ""
}

func (x *SniffRequest) GetWpaPsk() string {
	if x != nil {
		return x.WpaPsk
	}
	return ""
}

type SniffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	L7Protocols   []string               `protobuf:"bytes,4,rep,name=l7_protocols,json=l7Protocols,proto3" json:"l7_protocols,omitempty"`
	Hostnames     []string               `protobuf:"bytes,5,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SniffResponse) Reset() {
	*x = SniffResponse{}
	mi := &file_proto_darkprobe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SniffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SniffResponse) ProtoMessage() {}

func (x *SniffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SniffResponse.ProtoReflect.Descriptor instead.
func (*SniffResponse) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{4}
}

func (x *SniffResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SniffResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *SniffResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SniffResponse) GetL7Protocols() []string {
	if x != nil {
		return x.L7Protocols
	}
	return nil
}

func (x *SniffResponse) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

type TLSInspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSInspectRequest) Reset() {
	*x = TLSInspectRequest{}
	mi := &file_proto_darkprobe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSInspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSInspectRequest) ProtoMessage() {}

func (x *TLSInspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSInspectRequest.ProtoReflect.Descriptor instead.
func (*TLSInspectRequest) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{5}
}

func (x *TLSInspectRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TLSInspectRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TLSInspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // JSON or text summary of inspection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSInspectResponse) Reset() {
	*x = TLSInspectResponse{}
	mi := &file_proto_darkprobe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSInspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSInspectResponse) ProtoMessage() {}

func (x *TLSInspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_darkprobe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSInspectResponse.ProtoReflect.Descriptor instead.
func (*TLSInspectResponse) Descriptor() ([]byte, []int) {
	return file_proto_darkprobe_proto_rawDescGZIP(), []int{6}
}

func (x *TLSInspectResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_darkprobe_proto protoreflect.FileDescriptor

const file_proto_darkprobe_proto_rawDesc = "" +
	"\n" +
	"\x15proto/darkprobe.proto\x12\tdarkprobe\")\n" +
	"\x0fDiscoverRequest\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet\"w\n" +
	"\bHostInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"open_ports\x18\x04 \x03(\tR\topenPorts\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\"=\n" +
	"\x10DiscoverResponse\x12)\n" +
	"\x05hosts\x18\x01 \x03(\v2\x13.darkprobe.HostInfoR\x05hosts\"\x9f\x01\n" +
	"\fSniffRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\x12!\n" +
	"\fmonitor_mode\x18\x03 \x01(\bR\vmonitorMode\x12\x19\n" +
	"\bwpa_ssid\x18\x04 \x01(\tR\awpaSsid\x12\x17\n" +
	"\awpa_psk\x18\x05 \x01(\tR\x06wpaPsk\"\x82\x01\n" +
	"\rSniffResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12!\n" +
	"\fl7_protocols\x18\x04 \x03(\tR\vl7Protocols\x12\x1c\n" +
	"\thostnames\x18\x05 \x03(\tR\thostnames\"?\n" +
	"\x11TLSInspectRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\",\n" +
	"\x12TLSInspectResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xe0\x01\n" +
	"\x10DarkProbeService\x12C\n" +
	"\bDiscover\x12\x1a.darkprobe.DiscoverRequest\x1a\x1b.darkprobe.DiscoverResponse\x12<\n" +
	"\x05Sniff\x12\x17.darkprobe.SniffRequest\x1a\x18.darkprobe.SniffResponse0\x01\x12I\n" +
	"\n" +
	"TLSInspect\x12\x1c.darkprobe.TLSInspectRequest\x1a\x1d.darkprobe.TLSInspectResponseB<Z:github.com/straticus1/ads-darkapi-io/darkprobe/proto;protob\x06proto3"

var (
	file_proto_darkprobe_proto_rawDescOnce sync.Once
	file_proto_darkprobe_proto_rawDescData []byte
)

func file_proto_darkprobe_proto_rawDescGZIP() []byte {
	file_proto_darkprobe_proto_rawDescOnce.Do(func() {
		file_proto_darkprobe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_darkprobe_proto_rawDesc), len(file_proto_darkprobe_proto_rawDesc)))
	})
	return file_proto_darkprobe_proto_rawDescData
}

var file_proto_darkprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_darkprobe_proto_goTypes = []any{
	(*DiscoverRequest)(nil),    // 0: darkprobe.DiscoverRequest
	(*HostInfo)(nil),           // 1: darkprobe.HostInfo
	(*DiscoverResponse)(nil),   // 2: darkprobe.DiscoverResponse
	(*SniffRequest)(nil),       // 3: darkprobe.SniffRequest
	(*SniffResponse)(nil),      // 4: darkprobe.SniffResponse
	(*TLSInspectRequest)(nil),  // 5: darkprobe.TLSInspectRequest
	(*TLSInspectResponse)(nil), // 6: darkprobe.TLSInspectResponse
}
var file_proto_darkprobe_proto_depIdxs = []int32{
	1, // 0: darkprobe.DiscoverResponse.hosts:type_name -> darkprobe.HostInfo
	0, // 1: darkprobe.DarkProbeService.Discover:input_type -> darkprobe.DiscoverRequest
	3, // 2: darkprobe.DarkProbeService.Sniff:input_type -> darkprobe.SniffRequest
	5, // 3: darkprobe.DarkProbeService.TLSInspect:input_type -> darkprobe.TLSInspectRequest
	2, // 4: darkprobe.DarkProbeService.Discover:output_type -> darkprobe.DiscoverResponse
	4, // 5: darkprobe.DarkProbeService.Sniff:output_type -> darkprobe.SniffResponse
	6, // 6: darkprobe.DarkProbeService.TLSInspect:output_type -> darkprobe.TLSInspectResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_darkprobe_proto_init() }
func file_proto_darkprobe_proto_init() {
	if File_proto_darkprobe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_darkprobe_proto_rawDesc), len(file_proto_darkprobe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_darkprobe_proto_goTypes,
		DependencyIndexes: file_proto_darkprobe_proto_depIdxs,
		MessageInfos:      file_proto_darkprobe_proto_msgTypes,
	}.Build()
	File_proto_darkprobe_proto = out.File
	file_proto_darkprobe_proto_goTypes = nil
	file_proto_darkprobe_proto_depIdxs = nil
}
