// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/telemetry.proto

package grpcstream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DarkProbeTelemetry_StreamEvents_FullMethodName = "/darkapi.telemetry.v1.DarkProbeTelemetry/StreamEvents"
	DarkProbeTelemetry_ReportAlert_FullMethodName  = "/darkapi.telemetry.v1.DarkProbeTelemetry/ReportAlert"
)

// DarkProbeTelemetryClient is the client API for DarkProbeTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DarkProbeTelemetryClient interface {
	// Streams high-speed network telemetry from the darkprobed daemon to the DarkAPI gateway
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryResponse], error)
	// Sends a single high-priority alert (e.g. Rogue AP detected)
	ReportAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*AlertResponse, error)
}

type darkProbeTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewDarkProbeTelemetryClient(cc grpc.ClientConnInterface) DarkProbeTelemetryClient {
	return &darkProbeTelemetryClient{cc}
}

func (c *darkProbeTelemetryClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DarkProbeTelemetry_ServiceDesc.Streams[0], DarkProbeTelemetry_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryEvent, TelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DarkProbeTelemetry_StreamEventsClient = grpc.ClientStreamingClient[TelemetryEvent, TelemetryResponse]

func (c *darkProbeTelemetryClient) ReportAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*AlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, DarkProbeTelemetry_ReportAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DarkProbeTelemetryServer is the server API for DarkProbeTelemetry service.
// All implementations must embed UnimplementedDarkProbeTelemetryServer
// for forward compatibility.
type DarkProbeTelemetryServer interface {
	// Streams high-speed network telemetry from the darkprobed daemon to the DarkAPI gateway
	StreamEvents(grpc.ClientStreamingServer[TelemetryEvent, TelemetryResponse]) error
	// Sends a single high-priority alert (e.g. Rogue AP detected)
	ReportAlert(context.Context, *Alert) (*AlertResponse, error)
	mustEmbedUnimplementedDarkProbeTelemetryServer()
}

// UnimplementedDarkProbeTelemetryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDarkProbeTelemetryServer struct{}

func (UnimplementedDarkProbeTelemetryServer) StreamEvents(grpc.ClientStreamingServer[TelemetryEvent, TelemetryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDarkProbeTelemetryServer) ReportAlert(context.Context, *Alert) (*AlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlert not implemented")
}
func (UnimplementedDarkProbeTelemetryServer) mustEmbedUnimplementedDarkProbeTelemetryServer() {}
func (UnimplementedDarkProbeTelemetryServer) testEmbeddedByValue()                            {}

// UnsafeDarkProbeTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DarkProbeTelemetryServer will
// result in compilation errors.
type UnsafeDarkProbeTelemetryServer interface {
	mustEmbedUnimplementedDarkProbeTelemetryServer()
}

func RegisterDarkProbeTelemetryServer(s grpc.ServiceRegistrar, srv DarkProbeTelemetryServer) {
	// If the following call panics, it indicates UnimplementedDarkProbeTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DarkProbeTelemetry_ServiceDesc, srv)
}

func _DarkProbeTelemetry_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DarkProbeTelemetryServer).StreamEvents(&grpc.GenericServerStream[TelemetryEvent, TelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DarkProbeTelemetry_StreamEventsServer = grpc.ClientStreamingServer[TelemetryEvent, TelemetryResponse]

func _DarkProbeTelemetry_ReportAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkProbeTelemetryServer).ReportAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkProbeTelemetry_ReportAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkProbeTelemetryServer).ReportAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

// DarkProbeTelemetry_ServiceDesc is the grpc.ServiceDesc for DarkProbeTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DarkProbeTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkapi.telemetry.v1.DarkProbeTelemetry",
	HandlerType: (*DarkProbeTelemetryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAlert",
			Handler:    _DarkProbeTelemetry_ReportAlert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _DarkProbeTelemetry_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
